- gian.html
> Meu teste no github

- marcio.html
Foi incluido um arquivo marcio.html
> Incluindo arquivo marcio.html

- paginas/joasgarcia.txt
Aprendendo a realizar pull request.
> Adicionando joasgarcia.txt

- TestOMine
- teste.txt
> Pull Request para teste

- learn.json
correcting json, sorry my error
> adjusting learn.json

- index.html
- paginas/Arquivo41.txt
Adicionado paginas/arquivo41.txt para testar contribuição.
> Aprendendo a contribuir

- AndreBernardes.html
- index.html
- paginas/Arquivo42.txt
> commit 1.0

- paginas/arquivo20.txt
> reorganizacao dos diretorios, e implementacao da interface

- README.md
> Guida teste

- .gitignore
> Adicionado regras de desenvolvimento ide Netbeans ao .gitignore

- .gitignore
Acredito que o montante destes commits já pode ser considerado uma versão X.
Obrigado.
> Adicionado regra (*.*~ e *~) backup ao .gitignore

- index.html
- paginas/minha-pagina.html
> adicionei uma nova página

- BrunoBrandes.txt
> Adding file to test - it's working

- james.txt
Aprendendo a usar o gihub do jeito certo
> My first commit

- teste de colaboracao.php
Adicionei o meu primeiro ficheiro de colaboracao aqui no github.
> Adicionado um ficheiro de colaboracao

- lucaspaim.txt
Criando um arquivo .txt somente para aprender um pull request
> criando arquivo lucaspaim.txt para teste

- arquivo que eu criei.txt
Esse é um teste de pull request
> Adicionado novo txt de teste.

- README.md
- index.html
- paginas/arquivo43.txt
Seguindo o tutorial no **Tableless**, acrescentei um lista de chamada no _README.md_ e criei o meu arquivo no diretório e alterei o index.
> Fazendo a minha primeira contribuição

- victorhundo
> adicionando arquivo 'victorhundo'

- README.md
- rafascript.py
adicionando minha contribuição e aprendizado!
> Contribuindo com um fatorial feito em python, recursivo.

- README.md
- rotognin.php
> Adicionei minha participação

- README.md
> Contribuição de Henrique Emidio

- index.html
> Alteração teste

- macarena.py
> commit macarena.py

- hellogit.js
- learning.js
- paginas/hellogit.js
> Aprendendo GIT!

- ribeirojpn.js
Pull Request com documento ribeirojpn.js para praticar
> aprendendo a colaborar - ribeirojpn

- CésardBarros.php
- README.md
Feita a minha contribuição num projeto do GitHub ;D
> Contribuição dBarros.

- README.md
- dyegoalves
> Primeiro fork  e push request no Github

- README.md
- brunoAlvesdaSilva.php
Criando meu primeiro Pull Request para um pojeto no Github
> Bruno Alves

- LOL .-. .txt
- README.md
Update lista de nomes, e arquivo criado para testes
> Testando Git

- README.md
- Teste Paulo Correia.txt
> Teste de contribuição

- README.md
- index.html
- learning-to-contribute/paginas/arquivo45.txt
> Learning Github

- README.md
- dian-carlos.php
Meu teste de Fork e Pull Request que vi no seu tutorial do Tableless.
> Testando Fork e Pull Request no GitHub

- README.md
Contribuindo com outros projetos open source.
> Contribuindo em projeto forkado.

- PrimeiroPullRequest
- README.md
> Adicionado meu nome e um novo arquivo

- README.md
Contribuição a fim de aprender PullRequest, para futuramente contribuir com outros projetos
> Adicionando contribuição README.md - Aprendendo a fazer PullRequest

- README.md
- tami.html
Aprendendo o tutorial no tableless
> Comitando para o fork e colaboração

- DagmarCirino
> Dagmar Cirino

- i_was_here_FAA.md
I dont know what I should write here. I am noob.
> Add i_was_here_md file

- michael-artes-contribute.txt
> Comitando arquivo --> michael-artes

- matheusragoso.php
> Helo World

- index.html
- paginas/arquivo46.txt
Contribuindo para projeto open source
> Contribuindo em um projeto open source

- testing-contributions-on-github
Começando a aprender como contribuir em projetos open source.
> Primeiro pull request

- contribuicao.c
> Primeira contribuição

- felipeboso.txt
> Meu primeiro fork

- index.html
- paginas/arquivo47.txt
> New contributor

- paginas/LuanFork.rb
Pequena classe em ruby pro meu primeiro FORK ! :+1:
> Meu primeiro fork :)

- README.md
Incluindo contribuição no arquivo README.md
> Incluindo contribuição

- Paiva.py
> Tá ae o fork

- alisonamerico.html
Foi muito útil a iniciativa, parabéns!
> Foi inserido arquivo html agradecendo a iniciativa

- contribute.txt
Fazendo teste para contribuir com repositórios remotos. Obrigado pelo artigo.
> testeCommit

- myhello.txt
> hello world

- README.md
- murilo-eduardo-dos-santos-readme.txt
Adicionei um arquivo .txt com minhas informações para contato, coloquei meu nome (na ordem já correta), tirei espaços em branco e link para meu perfil no GitHub no README.md
> Muito bom este repositório, deseja estar dentro também!

- alessandroH.txt
> Teste de pull request a partir de um fork

- CassioAlmeida.rb
- README.md
> testando contribuição fork

- README.md
- isaque-bezerra.html
> Testing and learning to contribute

- ThaynanNadu.html
> Thaynan Nadu

- OlaGitHub.java
Commit do primeiro arquivo para teste.
> Minha primeira contribuição!!Vamos fortalecer a comunidade!

- learning-to-contribute/Lorem Ipsum.txt
- learning-to-contribute/luciano.txt
Aprendendo a usar pull request
> Pull Request Mapps

- testando.php
> Commit Carol

- leandro_ramos.rb
Estou seguindo o tutorial para aprender a contribuir com projetos opensouce.
Muito obrigado!
> Aprendendo a contribuir em projetos no Github.

- Gianluca.txt
- README.md
Olá. Li o artigo no http://tableless.com.br e fiz esta experiência.
Obrigado pela iniciativa.
> Teste de fork e pull-request

- README.md
- lorem
Olá, espero que aceite minhas modificações!
> Testando Pull Request

- TheNoviceDeveloper-RenanRoncarati.txt
> add The Novice Developer blog reference to teste how to make my first fork pullrequest

- README.md
- index.php
- paginas/index.php
> Learning to change the World! :3

- index.html
- paginas/arquivo48.txt
Primeiro teste para aprender como trabalhar em projetos open source no gtihub.
> Adicionado mais um link (para o arquivo 48) seguindo a ordem numérica

- LuisGustavo.txt
> My first commit !

- README.md
Foi colocada em ordem alfabética a lista com seus respectivos links no README.md
> Ordenação na lista de nomes com links no README.md

- README.md
> My first pull request (test)

- Noturnoo.md
> Apenas um teste

- william_mendes.md
Criando meu Readme de contribuição.
@WilliamMendesF
> Meu readme de contribuição.

- README.md
- william_mendes.md
> Editando Readme

- firstFork.html
> add firstFork

- learning-to-contribute/index.html
Hello,
follow my commit test to be merged in your code.
Thanks.
> new commit for test

- README.md
- tiao.js
> my first fork with pull request

- README.md
Teste de atualização do github, contribuindo com projeto.
> Treinando fork com atualizacao remota

- WAD Form Test/data/se_1505658_student.sql
- WAD Form Test/se_1505658.sql
- WAD Form Test/se_1505658_form.php
- WAD Form Test/se_1505658_index.php
- WAD Form Test/se_1505658_insert.php
- WAD Form Test/se_1505658_style.css
I have added new item. Thank you for reviewing!
> add new item

- HacktoberFest_USP.txt
> Adicionar um arquivo para o HacktoberFest

- Hacktoberfest.txt
> add arquivo txt para hacktoberfest

- README.md
Thanks for this opportunity to practice.
> PR by Emerson Bezerra

- README.md
- **Adicionei o meu nome** no `README.md`
> Deixando a minha contribuição

- README.md
- testing.ipynb
> contribution

- jhoabe.html
> Testando meu primeiro PR

- README.md
- devdec.html
Adicionei meu devdec.html e organizei a lista de contribuidores em ordem alfabetica.
> Fiz minha contribuição
